- docs/source/conf.py
Taken directly from wpilib, there may be extraneous options configured
> Update Latex configuration to fix PDF builds

- docs/source/programming_resources/shared/configuring_android/Configuring-Your-Android-Devices.rst
- docs/source/programming_resources/shared/managing_control_hub/Managing-a-Control-Hub.rst
- docs/source/programming_resources/tutorial_specific/android_studio/enabling_developer_options/Enabling-Developer-Options.rst
- docs/source/programming_resources/tutorial_specific/onbot_java/onbot_java_reference/OnBot-Java-Reference-Info.rst
Update more broken/redirected links
> Fixing More Broken/Redirected Links

- docs/source/programming_resources/shared/managing_control_hub/Managing-a-Control-Hub.rst
- docs/source/programming_resources/shared/managing_smartphone_ds/Managing-a-Smartphone-Driver-Station.rst
- docs/source/programming_resources/shared/managing_smartphone_rc/Managing-a-Smartphone-Robot-Controller.rst
> Hopefully last link fix for now.

- docs/Makefile
- docs/requirements.txt
- docs/source/requirements.txt
Builds html and automatically starts webserver on open port then automatically opening default browser.
> Add autobuild to makefile

- .github/workflows/link-check.yaml
> Periodic checks of links (every 12 hours)

- .github/workflows/publish.yaml
- .github/workflows/pull-request.yaml
- docs/source/conf.py
This will allow the worflows to dynamically deal with changes to project name. If not, it will throw a big hissy fit.
> Fix workflows

- docs/source/cad_resources/autodesk/autodesk.rst
- docs/source/cad_resources/index.rst
- docs/source/cad_resources/ptc/ptc.rst
- docs/source/cad_resources/solidworks/solidworks.rst
- docs/source/conf.py
- docs/source/index.rst
- docs/source/stubs/autodesk_fusion_360_resources.rst
- docs/source/stubs/mentor_technical_resources.rst
- docs/source/stubs/ptc_onshape_resources.rst
- docs/source/stubs/rookie_teams.rst
- docs/source/stubs/solidworks_resources.rst
- docs/source/stubs/veteran_teams.rst
Add CAD resource pages with instructions on how to acquire FIRST-specific licenses.
> Add CAD resources

- docs/source/_static/css/ftc-rtd.css
> Fix issue #42

- docs/source/conf.py
- docs/source/programming_resources/tutorial_specific/android_studio/installing_android_studio/Installing-Android-Studio.rst
SolidWorks more like `<REDACTED>`
> Fix linkchecker to work without bypass for Solidworks

- docs/source/ftc_ml/implement/android_studios/android-studios.rst
- docs/source/ftc_ml/implement/blocks/blocks.rst
- docs/source/ftc_ml/implement/obj/obj.rst
- docs/source/ftc_ml/index.rst
- docs/source/index.rst
- docs/source/programming_resources/vision/tensorflow_ff_2021/tensorflow-ff-2021.rst
- docs/source/stubs/external_tools.rst
Update FTC-ML page to be more descriptive
> Update FTC-ML page to be more descriptive

- docs/source/programming_resources/index.rst
We need to add the FIRST Website's resource library to the Programming Resources section.
> Add FIRST Website Links to Programming Resources

- .github/workflows/pull-request.yaml
Change PR Check to be more like publisher.
> Dodo to Canary

- docs/source/conf.py
- docs/source/sponsors/software/software.rst
- docs/source/todo.rst
Monday.com will be hosting a webinar, add webinar details.
> Add info about Monday.com webinar

- docs/source/form/form.rst
- docs/source/index.rst
> Add feedback form

- docs/source/form/form.rst
- docs/source/index.rst
> Update Feedback Form Link/Contents

- docs/source/programming_resources/vision/webcam_controls/webcam-controls.rst
Fixes #107  and cleans up Java Doc References
> Cleanup Webcam Controls Page

- .github/workflows/publish.yaml
- docs/requirements.txt
- docs/source/conf.py
- docs/source/programming_resources/vision/webcam_controls/webcam-controls.rst
> Add Google Analytics through FTC-owned fork of sphinxcontrib-googleanalytics

- docs/source/overview/ftcoverview.rst
Now that Google Analytics is enabled, let's track video plays.
> Enable jsapi to allow tracking plays of videos

- docs/source/overview/ftcoverview.rst
- docs/source/persona_pages/rookie_teams/rookie_teams.rst
Quick cleanup of a couple places where FIRST wasn't italicized.
> Italicize FIRST in links and text

- .github/workflows/publish.yaml
- .github/workflows/pull-request.yaml
- docs/Makefile
- docs/requirements.txt
- docs/source/conf.py
> Add Official Make File Option

- docs/source/sponsors/software/software.rst
> Remove Monday.com

- docs/source/tos/tos.rst
Orphaned page, still needs to be added to website footer
> Add Terms of Service Page

- .github/workflows/publish.yaml
Forgot to add the COOKIEBANNER enable/disable secret to the publish yaml.
> Propagate CookieBanner Secrets

- docs/requirements.txt
- docs/source/cad_resources/index.rst
- docs/source/conf.py
- docs/source/control_hard_compon/ds_components/index.rst
- docs/source/control_hard_compon/index.rst
- docs/source/faq/faqs.rst
- docs/source/ftc_ml/managing_tool/index.rst
- docs/source/ftc_ml/optimize_videos/optimize-videos.rst
- docs/source/ftc_sdk/overview/index.rst
- docs/source/ftc_sdk/updating/index.rst
- docs/source/game_specific_resources/ftcqa/ftcqa.rst
- docs/source/hardware_and_software_configuration/index.rst
- docs/source/robots.txt
Add more meta tags
Add sitemap generations
> SEO Optimizations

- docs/source/ftc_ml/implement/blocks/blocks.rst
- docs/source/ftc_ml/implement/obj/obj.rst
We need to update the tutorials to talk about the model file manager.
> Update ftc-ml tutorials

- .github/workflows/pull-request.yaml
- README.md
After moving to RTD the status badge has to be updated
> Post RTD transition cleanup

- docs/source/control_hard_compon/ds_components/components/components.rst
- docs/source/control_hard_compon/ds_components/index.rst
- docs/source/control_hard_compon/index.rst
- docs/source/control_hard_compon/rc_components/encoders/encoders.rst
- docs/source/control_hard_compon/rc_components/hub/hub.rst
- docs/source/control_hard_compon/rc_components/hub/ports/exh-ports.rst
- docs/source/control_hard_compon/rc_components/hub/ports/std-ports.rst
- docs/source/control_hard_compon/rc_components/motors/motors.rst
- docs/source/control_hard_compon/rc_components/power_distr/power-distr.rst
- docs/source/control_hard_compon/rc_components/sensors/sensors.rst
- docs/source/control_hard_compon/rc_components/servos/servos.rst
- docs/source/control_hard_compon/rc_components/uvc/uvc.rst
- docs/source/ftc_sdk/overview/index.rst
- docs/source/ftc_sdk/updating/controlhub_os/Updating-the-Control-Hub-OS.rst
- docs/source/ftc_sdk/updating/driverhub_os/Updating-the-Driver-Hub-OS.rst
- docs/source/ftc_sdk/updating/ds_app/Updating-the-DS-App.rst
- docs/source/ftc_sdk/updating/hub_firmware/Updating-Hub-Firmware.rst
- docs/source/ftc_sdk/updating/rc_app/Updating-the-RC-App.rst
- docs/source/hardware_and_software_configuration/connecting_devices/connecting_color/connecting-color.rst
- docs/source/hardware_and_software_configuration/connecting_devices/connecting_motor/connecting-motor.rst
- docs/source/hardware_and_software_configuration/connecting_devices/connecting_touch/connecting-touch.rst
- docs/source/index.rst
- docs/source/manuals/game_manuals/game_manuals.rst
- docs/source/persona_pages/mentor_tech/mentor_tech.rst
- docs/source/persona_pages/rookie_teams/rookie_teams.rst
- docs/source/persona_pages/veteran_teams/veteran_teams.rst
- docs/source/programming_resources/shared/control_system_intro/The-FTC-Control-System.rst
Thanks to @WestsideRobotics for all the corrections
> Many Small Updates

- docs/source/conf.py
Fixes broken link on cad resources page for autodesk
> Fix broken link

- docs/source/conf.py
> Add support for translations

- docs/source/programming_resources/index.rst
- docs/source/programming_resources/vision/camera_calibration/camera-calibration.rst
Camera calibration OpMode coming in offseason SDK 8.2, especially helpful for teams choosing to use fiducial marker systems.
> Adding Camera Calibration documentation.

- .readthedocs.yaml
> Update .readthedocs.yaml for ReadTheDocs

- docs/source/conf.py
> Re-add Accidentally Removed Booklets

- docs/source/programming_resources/vision/java_tfod_opmode_custom/java-tfod-opmode-custom.rst
* Updating TFOD Tutorials and Fixing Blog
> Updating TFOD Tutorials and Fixing Blog (#223)

- docs/requirements.txt
No errors on my machine (haven't tried building pdf).
Closes #229
> Update Sphinx to 4.5.0

- docs/source/game_specific_resources/blog/blog.rst
Change to https version so it doesn't not violate browser security standards.
> Fix Blog IFrame

- docs/source/ftc_sdk/updating/rc_app/Updating-the-RC-App.rst
Changes made per @WestsideRobotics request
> Correct the Step 1 instructions for updating RC app on Control Hub via Manage Page 

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .github/workflows/devcontainer.yaml
- .vscode/extensions.json
- .vscode/settings.json
- .vscode/tasks.json
- docs/Makefile
Allows for easier use with VS Code out of the box as well as support for Codespaces
> Add Devcontainer and VSCode configs

- docs/source/sponsors/discounts/discounts.rst
Per FIRST finance and accounting we will not be listing any discount codes from vendors on any FIRST official channels of communication.
> Remove discount vendor codes

- docs/source/tech_tips/tech-tips.rst
Update power calculator javascript so that the calculate() function is called to recalculate power whenever the "Time per 60" value or unit is changed.
> Update power calculator javascript

- docs/source/apriltag/vision_portal/apriltag_intro/apriltag-intro.rst
"...Tech Challenge *nuses* a common..." -> "...Tech Challenge *uses* a common..."
> Fix a typo

- docs/source/persona_pages/rookie_teams/rookie_teams.rst
> Remove pre-match checklist

- docs/source/tech_tips/tech-tips.rst
Updating calibration tech tip to include unofficial dualshock tools effort to calibrate a DualShock 4 and DualSense gamepad in case they begin to drift. Thanks to QwertyChouskie for the tip.
> Updating Gamepad Calibration Tech Tip

- docs/source/cad_resources/autodesk/autodesk.rst
- docs/source/manufacturing/3d_printing/filament_choice/advanced_filaments/advanced_filaments.rst
- docs/source/persona_pages/coach_admin/coach_admin.rst
> Sample team budget fix

- .github/workflows/link-check.yaml
- .github/workflows/pull-request.yaml
- dependencies
- docs/requirements.txt
At long last it arrives (hopefully)
> Diff Linkchecker

- .github/workflows/link-check.yaml
- .github/workflows/pull-request.yaml
- dependencies
- docs/requirements.txt
> Diff Linkchecker P2

- .github/workflows/link-check.yaml
- .github/workflows/pull-request.yaml
https://github.com/actions/upload-artifact recommends updating to v4 of the artifact upload action.
> Update artifact upload to version 4

- docs/source/tech_tips/tech-tips.rst
Add Google AI Studio tech tip.
> Update Tech Tips for Google AI Studio

- docs/source/color_processing/color-processing-introduction/color-processing-introduction.rst
- docs/source/programming_resources/index.rst
Add documentation stub for FTC Color Processing.
> Add FTC Color Processing Documentation Stub

- .github/workflows/link-check.yaml
- docs/requirements.txt
- docs/source/conf.py
- docs/source/tech_tips/tech-tips.rst
Uses in house extension that adds the following functionality
- Saves Link Checker logs to JSON files with more detail
- Adds extension level functionality of running diff checks (see what errors are new)
- Adds configurability on what types of link failures to error on
> Real Diff Link Checker

- .github/workflows/pull-request.yaml
Specify ubuntu-22.04 so that OS tooling changes can't break the workflow.
> Don't use ubuntu-latest

- docs/source/programming_resources/shared/managing_control_hub/Managing-a-Control-Hub.rst
Fixes: https://github.com/cmacfarl/ftcdocs/actions/runs/13021889865/job/36324104803
> Fix 301 redirect on helpdeskgeek.com

- docs/source/conf.py
> Update PDF Header Take 2

- docs/source/faq/faqs.rst
- docs/source/game_specific_resources/playing_field_resources/playing_field_resources.rst
- docs/source/manuals/game_manuals/game_manuals.rst
- docs/source/sponsors/software/software.rst
inaccuracies on judging feedback, references to GM1/2, dangling references to embeds that don't exist, remote game play reference, trello free plan changes
> fix: general dated information

- docs/source/persona_pages/coach_admin/coach_admin.rst
> Remove budget box from coach_admin.rst
